version: '3'
services:
  db-cats-api:
    image: postgres:16
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: cats-api

